############# Indonesian navigation ##############

# main menu
[[main]]
name = "Beranda"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Jasa"

[[main]]
parent = "Jasa"
name = "Bangun baru"
pageRef="/jasa/bangun-baru"
weight=1

[[main]]
parent = "Jasa"
name = "Renovasi"
pageRef="/jasa/renovasi"
weight=2

[[main]]
parent = "Jasa"
name = "Perbaikan"
pageRef="/jasa/perbaikan"
weight=3

[[main]]
parent = "Jasa"
name = "Las & aluminium"
pageRef="/jasa/las-dan-aluminium"
weight=4

[[main]]
parent = "Jasa"
name = "Instalasi listrik"
pageRef="/jasa/instalasi-listrik"
weight=5

[[main]]
name = "Tentang kami"
pageRef="/about"
weight = 3

[[main]]
name = "Blog"
pageRef="/blog"
weight = 4


[[main]]
name = "Kontak"
pageRef="/contact"
weight = 5


# footer menu
[[footer]]
name = "Tentang kami"
pageRef="/about"
weight = 1

[[footer]]
name = "Blog"
pageRef="/blog"
weight = 2

[[footer]]
name = "Kebijakan Privasi"
pageRef="/pages/privacy-policy"
weight = 3
