############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Services"

[[main]]
parent = "Services"
name = "Build new"
pageRef="/services/build-new"
weight=1

[[main]]
parent = "Services"
name = "Renovation"
pageRef="/services/renovation"
weight=2

[[main]]
parent = "Services"
name = "Repair"
pageRef="/services/repair"
weight=3

[[main]]
parent = "Services"
name = "Welding & aluminium"
pageRef="/services/welding-and-aluminium"
weight=4

[[main]]
parent = "Services"
name = "Electrical installation"
pageRef="/services/electrical-installation"
weight=5

[[main]]
name = "About Us"
pageRef="/about"
weight = 3

[[main]]
name = "Blog"
pageRef="/blog"
weight = 4


[[main]]
name = "Contact"
pageRef="/contact"
weight = 5


# footer menu
[[footer]]
name = "About Us"
pageRef="/about"
weight = 1

[[footer]]
name = "Blog"
pageRef="/blog"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef="/pages/privacy-policy"
weight = 3
